export enum TransactionPaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  BANK_SLIP = 'BANK_SLIP',
  CASH = 'CASH',
  PIX = 'PIX',
  OTHER = 'OTHER',
  CRIPTO = 'CRIPTO'
}